### ISSUE TITLE
Launcher 5.0 Erro 404

### ISSUE THREAD

**Issue by psycodeliccircus** [MrDarkSkil/Launcher_Multigaming#25]
Hello Friend.
I did everything to run the launcher but it is always giving **404 error** in the launcher.
I checked all files anyway even so I'm still having **404 error** can you help me?

@MightySCollins @iWirk @MrDarkSkil @bozoweed @FlashModz

**Comment by MightySCollins** [comment]
Please don't mention everyone... Errors like these are usually server configuration issues and not the contributers fault. It just reduces the chance of someone wanting to help you. 

I also recommend you provide some more information like your PHP version and server setup.

**Comment by psycodeliccircus** [comment]
Apache/2.4.23 (Win32) OpenSSL/1.0.2h PHP/5.6.28
mysqlnd 5.0.11-dev - 20120503 - $Id: 76b08b24596e12d4553bd41fc93cccd5bac2fe7a $
@MightySCollins

**Comment by FlashModz** [comment]
Hello @psycodeliccircus ,

give me your Website adresse and your config file to your launcher.
Thanks.

No informations = No Help

**Comment by MrDarkSkil** [comment]
Put your launcher_name.exe and rename it launcher.exe into the games/launcher/launcher.exe and tell me if it work .

**Comment by psycodeliccircus** [comment]
@MrDarkSkil I did it here on my machine and it worked but when I step into it it gives the error can help me friend?

**Comment by FlashModz** [comment]
@psycodeliccircus go to my TS, ts.flashmodz.fr

**Comment by psycodeliccircus** [comment]
@FlashModz ok

**Comment by RenegadosServidores** [comment]
I am partner of psycodeliccircus Flash, are you in your TS3 yet?

**Comment by RenegadosServidores** [comment]
When possible send us what time we can go there to explain the problem, 
really thanks for help

**Comment by FlashModz** [comment]
i'm online now :)

**Comment by FlashModz** [comment]
The problem is your web server.
You have not followed the steps for configuring your Webserver.

You do not have access to your apache configuration and you can not change the owner of the folder to www-data.

Come back to us with an exact configuration and we will help you with pleasure

**Comment by RenegadosServidores** [comment]
Thanks man, i wil lfind the problem and come back later, really thanks for your help

Rodrigo Varella
Florianópolis, SC - Brasil



--------------------------------------------
On Fri, 27/1/17, FlashModz <notifications@github.com> wrote:

 Subject: Re: [MrDarkSkil/Launcher_Multigaming] Launcher 5.0 Erro 404 (#25)
 To: "MrDarkSkil/Launcher_Multigaming" <Launcher_Multigaming@noreply.github.com>
 Cc: "Renegados Servidores" <vruet@yahoo.co.uk>, "Comment" <comment@noreply.github.com>
 Date: Friday, 27 January, 2017, 11:01
 
 i'm online now :)
 
 —
 You are receiving this because you commented.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by RenegadosServidores** [comment]
i will find how change this configuration and come back, really thanks !

Rodrigo Varella
Florianópolis, SC - Brasil



--------------------------------------------
On Fri, 27/1/17, FlashModz <notifications@github.com> wrote:

 Subject: Re: [MrDarkSkil/Launcher_Multigaming] Launcher 5.0 Erro 404 (#25)
 To: "MrDarkSkil/Launcher_Multigaming" <Launcher_Multigaming@noreply.github.com>
 Cc: "Renegados Servidores" <vruet@yahoo.co.uk>, "Comment" <comment@noreply.github.com>
 Date: Friday, 27 January, 2017, 12:47
 
 The problem is your web server.
 
 You have not followed the steps for configuring your
 Webserver.
 You do not have access to your apache configuration and
 you can not change the owner of the folder to www-data.
 Come back to us with an exact configuration and we will
 help you with pleasure
 
 —
 You are receiving this because you commented.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by MrDarkSkil** [comment]
The problem is solved ?

**Comment by MrDarkSkil** [comment]
No response ?
Ok i close this Issue
